
spring:  redis:    host: 192.168.27.128
    jedis:      pool:        max-idle: 100
  session:    store-type: redis
    timeout: 1800
    
    
    

#spring.redis.pool.max-active=100

