spring:
  application:
    name: SCW-USER
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://192.168.27.128:3306/atcrowdfunding210326?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    filters: stat
  redis:    host: 192.168.27.128
    port: 6379

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: SCW-USER
    prefer-ip-address: true

server:
  port: 8000

logging:  file:
    name: scw-user.log
  level:
    com.atguigu.scw: debug
    
sms:
  host: https://intlsms.market.alicloudapi.com
  path: /comms/sms/sendmsgall
  method: POST
  appcode: f936a655de2747bf911650b87a1dcc80
  validity: 5

swagger2:
  enable: true
